// <auto-generated />
using System;
using Gerenciamento.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gerenciamento.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260327043732_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gerenciamento.Api.Models.Categoria", b =>
                {
                    b.Property<Guid>("idCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("finalidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idCategoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Gerenciamento.Api.Models.Pessoa", b =>
                {
                    b.Property<Guid>("idPessoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("idade")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("idPessoa");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("Gerenciamento.Api.Models.Transacao", b =>
                {
                    b.Property<Guid>("idTransacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("categoriaidCategoria")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<Guid>("idCategoria")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("idPessoa")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("idTransacao");

                    b.HasIndex("categoriaidCategoria");

                    b.HasIndex("idPessoa");

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("Gerenciamento.Api.Models.Transacao", b =>
                {
                    b.HasOne("Gerenciamento.Api.Models.Categoria", "categoria")
                        .WithMany()
                        .HasForeignKey("categoriaidCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gerenciamento.Api.Models.Pessoa", "pessoa")
                        .WithMany("transacoes")
                        .HasForeignKey("idPessoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categoria");

                    b.Navigation("pessoa");
                });

            modelBuilder.Entity("Gerenciamento.Api.Models.Pessoa", b =>
                {
                    b.Navigation("transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
